package edu.unc.ceccr.chembench.persistence;


import java.util.List;

public class Descriptors implements java.io.Serializable {
    //For one compound and one descriptor generation program, this class stores all the descriptors.
    //e.g., the string "descriptorValues" could contain the 900 values generated by Dragon for lorazepam.
    private int compoundIndex;
    private String compoundName;
    private List<Double> descriptorValues;

    public Descriptors() {
    }

    public List<Double> getDescriptorValues() {
        return descriptorValues;
    }

    public void setDescriptorValues(List<Double> descriptorValues) {
        this.descriptorValues = descriptorValues;
    }

    public String getCompoundName() {
        return compoundName;
    }

    public void setCompoundName(String compoundName) {
        this.compoundName = compoundName;
    }

    public int getCompoundIndex() {
        return compoundIndex;
    }

    public void setCompoundIndex(int compoundIndex) {
        this.compoundIndex = compoundIndex;
    }

}
